Let's play in the Land of Makebelief today. Imagine the Blackrock EFF is aproved. The price of a sat pumps to $0.001. The fiat maxis like on the microblogging company formally known as Twitter rejoice. We have regulatory clarity. The custodial lightning wallets get banned like online poker. NGU for the win. Bitcoin becomes another investment locked into the third party trust paradigm, but nobody uses it as peer-to-peer electronic cash. They sell their bitcoin for CBDC's to buy groceries and pay for their car payment(The van they live in) The government can keep tabs on them no matter where they're parked. Yay suits!

![black hole rock](https://i.nostr.build/3qwW.png)

But the US goober-mint decides to levy an emergency inflation tax on anyone who sells their blackRock ETF's. Now, suit-maxi Bitcoiner Bob is required to pay a 50% tax on top of his 15% capital gains tax. Lucky for you, the capital gains tax is programed right into the CBDC so you won't need a CPA. The CPI is "going down", stabilized at 3.3%, but your grocery bill, electric bill, and everthing else you need day to day inexplicably rises 15% every year.  Yay democracy!

## Meet Alice, Living On The Bitcoin Standard

![candle](https://i.nostr.build/7VPv.jpg)

Alice is sophisticated. Alice  is sassy. Not so long ago, she decided **she would not send her fiat to Mr. Blackrock**. She asked herself, **why buy Black rocks when I can buy orange coins**? On second thought,  **why send fiat to some corporation at all? Why not sell stuff for bitcoin instead?** Be your own business and be your own bank. She gets on nostr. She makes candles and sells them for Bitcoin on clients like [Shopster](https://shopstr.store/) and [Plebian Market.](https://plebeian.market/) She uses some of her profits to buy coffee and beef with Bitcoin. She saves the rest because she subscribes to Matt Odell's newsletter:  She meticuliousy follows the advice of this daily newsletter. "Stay humble. Stack Sats."

Alice sells candles. She has a job, but this side hustle earns about $500 worth of bitcoin every month. She still thinks inflation sucks, but at least she is stacking value that cannot be debased. Therefore she expects to retire in about 2 more halfings. In about 8 years, she plans on buying some land, hooking her van up to water and sewage on this land and growing most of her food. She's rich, according to fiat standards, but doesn't see the need to waste sats on status symbols. Status symbols are a security holes.

# The Importance of The Circular Economy

The circular economy is the bitcoin economy. It's composed of hardcore Bitcoiners who use Bitcoin as peer to electronic cash. They prefer this electronic cash to fiat trash. Fiat cash is guaranteed to buy less and less stuff over time. Therefore, those who take part in the circular economy trade goods and services for bitcoin instead of trading bullshit pay for Bitcoin. Some argue there is no circular economy. There is just the economy and it does not make sense to spend sats when it goes up in value so much. I think this is misguided and will explain why in a little bit. For now, we will d efine what the circular economy means: Simply buying goods and services with bitcoin.

Bitcoin used in the circular economy is outside "the system". If this Bitcoin is only used to buy goods and services between Bitcoiners, that p2p electronic cash will never be exchanged for fiat tr, it will be used to buy more things like coffee and and beef. If you're one of the NGU maxis, think about what that means for a moment. The bitcoin used in the circular economy will remain off the exchanges. When the exchagnes run out of bitcoin, what do you think will happen to the "bitcoin price?" The less Bitcoin on the exchanges, the more valuable it becomes. Therefore, the more people who opt to buy clothes, and coffee using bitcoin in the circular economy instead of using credit cards to buy low time preference crap at the mall, the less bitcoin will be available for trading shitcoins like ETH and USD on the exchanges. That's like NGU to the moon.

When viewed from this perspective, **stacking sats and buying goods and services from people who accept Bitcoin for their products is akin to stacking harder**. In other words, **more sats are stacked in aggregate**.  Ben Franklin once said, "a penny saved us a penny earned". By the same logic, a sat spent in the circular economy is a sat stacked. I'm not saying waste your sats and spend frivolously. Spend sats carefully. Set a budget . Spend on things you will use. But it's better to spend Bitcoin on products and services offered by hardcore Bitcoiners than spend fiat on Amazon. Spending Fiat on Amazon does not put more Bitcoin into the hands of another fellow Bitcoiner. Spending for more things using bitcoin will create the Intransigent Minority Cory from Swan wrote about.

*   Buying some art at Home Goods? Why not support an artist on nostr?.

*   Do you buy coffee grounds? Buy coffee grounds with bitcoin.

*   Need to cover your bald head? Buy a hat with bitcoin.

### WTF Are Non-Paid ADs?

You have undoubtedly seen paid advertisements and affiliate marketing.  This is not that. V4V ads are more like word of mouth adverting. This makes my ads free from influence. These companies are free to zap me after the fact, but I came up with this list on my own because I believe in these companies and have used them. One of the reasons I started writing a blog about using bitcoin is because I wanted to promote the circular economy. I believe the best way to support this economy is to tell the world about companies that accept bitcoin for payment. In case you didn't get the memo, Cory Klippsten says [we need ten million bitcoiners to become an intransigent minority](https://www.linkedin.com/pulse/ten-million-bitcoiners-intransigent-minority-cory-klippsten) for hyperbitcoinization to occur.  To me, this not only means stacking sats, but also using bitcoin as p2p cash. This is not to say saving is unimportant. It is important to save, but you need to eat. Buy some groceries with bitcoin. I don't really need to drink coffee, buy I do, so I will buy coffee with sats. You might think, I would rather spend $ 12   bucks  on Foldgers than  $ 20 on bitcoin coffee. I'll buy sats with the difference.

Maybe, but if you buy coffee with sats, even sats you insta-converted from fiat on Strike, you contribute to taking more bitcoin off the exchanges. When I bought a 3D printed heater case from Crypto Cloaks, I know those sats most won't end up on an exchange. I assume the same is true for the bitcoin coffee sellers. This is not a new idea. My brother in law owns a business. He likes to shop locally even though he knows he can find a better price at WalMart. Shopping locally helps support his local economy. He wants the money he earns to stay in his community. Bitcoin is a world wide monetary network, but we have our own "local bitcoin economy." That local economy  happens to be on The Internet, so you might buy stuff from someone in your own town, or across the world. I may live in California, but I still consider products I buy with Bitcoin from companies located in Canada my local community. In some ways that community is even more local than my meat space community. It's in my pocket. I don't even need to leave my house.

That's more important than an ETF in my opinion. That's why I support participating in the circular economy. The problem bitcoin solves, the Byzantine General's problem, cannot be solved by trusting a third party like Black Rock. The problem bitcoin solves can only be solved if bitcoin is used as peer to peer electronic cash and saved in the bitcoin network. I support companies that support this mission of keeping bitcoin native. You won't see ads for gold or hardware wallet's I don't like or have never used . Bitcoin Panties might be a fine company, but I don't endorse bitcoin panties, because I don't wear panties. There are a few companies I believe have great potential, but are not ready for the masses quite yet. My V4V ads attempt to highlight companies like this and find the best solutions to my own problems.

### I Thought The Value 4 Value Model Did Not Use Ads

I disagree. The Value 4 Value model does not use paid ads. These are not those ads. Paid ads often seem disingenuous. Tom Brady is or was a great football player(So I hear) Jillions of people trusted his opinion about FTX because he handles pig-skin balls very well. People associate his pig-skin ball throwing skills with his ability to pick great crypto companies. It's a common rhetorical trick, but it's dumb. That's like saying I can predict the winner of the next SuperBowl because I know how to create a vanity address.  This is not true because cryptography and football have nothing to do with each other. I kinda get why people like Jordan's shoes, but doubt sneakers made by Chinese children will improve my jump shot. Nor do I believe Mike would he wear Hanes underwear if Hanes didn't they did not pay him.  I often feel the same way when hearing some bitcoiner podcasts talk about certain products. Block-Fi is an obvious examples, but I often feel the same about some of the hardware wallets people shill. I don't have anything bad to say about BitBox02, but I've never used the wallet, so I would not feel comfortable shilling it, even if they offered to pay me.  I'm sure it's a fine wallet. I wish BitBox all the best, I just can't vouch for them because I have never used one. I have a ledger nano that is about as old as a certain podcasters ledger nano, but I do not recommend them because I often get phishing emails from their official website among other things. They would pay me \$20 for every customer I refer them if I joined their affiliate program, but I can't accept that money in good conscious.

So these are not ads for Hanes underwear. If the Blackrock ETF gets approved, you won't see me shilling them because I think holding a bitcoin ETF is almost as dumb as letting some website convince you that you own rock jpegs. I don't believe in ETF's or NFT's's

The following is a list of business that I do use:

[Coinkite](https://coinkite.com/)

You have heard of them for sure, the maker of the world famous Cold Card. If you don't have a cold card, you need to get your shit in order, but the company makes at least 50 products.  I don't have a discount code for this company, but listen to a bitcoin podcast and I'm sure you will find one. Coin kite does a lot of other cool shit too, like the satschip, a product designed for artists.  NFT's are a scam, but physical art is a real thing. Artists who add the satschip to their physical artworks can throw a photo of the artwork on the CoinKite website.  These jpegs are not NFT's. They are not Ordinals. They are art with a chip that works similar to the Tap Signer, except the seed can never be revealed. It ties the physical paining, a , et al. to the bitcoin blockchain. It's neat way of tying art to digital scarcity without all the scammy bullshit associated with NFT's

[Bitrefill](https://www.bitrefill.com/us/en/) let's Me buy gift cards with bitcoin. I used to use it to pay my bills, but they have since discontinued that service. I still think it's a great company and use it as a way to get discounts on certain stores like CryptoCloaks.



\[CryptoCloaks]\(<https://www.cryptocloaks.com/>) is a company that sells  3D printed items for sats. I hae bought quite a few things off them. Most recently, a case that my S9 which has been converted into a heater. He has a lot of other cool stuff too. Check him out.

[BitcoinHatGuy](https://bitcoinhatguy.com/) has sold hats for bitcoin for decades and I have spent more sats on these hats than I feel comfortable admitting, but have never regretted my purchases. In real life, I'm one of those wierdos that wears the same thing everyday: Black T-Shirt and Gray pants, but I have an extensive hat collection. I buy most of my hats with bitcoin and most of those hats were bought from BTChatGuy. They're great, cheaper than MLB or even minor league baseball hats and I don't watch sports anyway. If you wear hats, buy a hat from this dude.

[Robosats](https://learn.robosats.com/)

Bitcoin exchanges are some of the biggest spenders in the bitcoin content creation market. They are the bread and butter for content creators.  This makes sense, because they also get the most in fees. According to David Bennet from the Bitcoin and Podcast, The Cash App had over a billion bucks in revenue from bitcoin sales alone. Good. I'm happy for the Block, but smaller bitcoin only exchanges like RoboSats don't get the exposure they deserve because they don't have the marketing budget.  RoboSats is a peer to peer exchange.  It's only on TOR, but they also have an app on the Andoroid store for those too timid for TOR.

Robosats is a bitcoin escrow service. They hold bitcoin in escrow and wait for conformation that payment has been recieved. Bitcoin sellers generally sell for about 5% above market value to provide KYC Free Sats to customers. Fiat settlements are made using the Cash App, Strike, or even Amazon gift cards. We should market the p2p exchanges like this more. Robosats  incentives this by giving users or referal codes. Refer someone to RoboSats using your referral code and you will get 100 sats for each trade. I would like to see people shill RoboSats and pick up these sats on social media. So I am not only asking you to use RoboSats, but I am also asking you to shill it.  I had nodeless.io on the list, but the tyrannical government of Canada shut it down. When I attempt to orange pill normies, the objection I most often need to overcome is "Bitcoin can never work because the government\[state] will shut it down. The 100k bitcoiners in the world know it does not work that way, but most CPI believers think the government just needs to shut down the single bitcoin computer to take it all away.  Perception is reality as they say. And yeah, we won't all turn off our bitcoin mining heaters or shut off our nodes, but I have seen online Poker get decimated by government policies. They did not succeed at ending online poker, but they essentially ended access to online poker for anyone with a sub 120 IQ.  If we want bitcoin to be for everybody, we need to make it easy for people to buy non-KYC bitcoin. RoboSats is making that their mission.

[Satoshi Coffee Co](https://sats.coffee)

I just learned about this company while searching for nostr icons on github.  Full disclosure, I have not vetted them yet because I just made my first order. If this coffee is any good, I'll let you know. I'll add a picture of the coffee when it gets here.  You know what else?  It's not as cheap as Foldgers, but I'm tired of drinking fucking Foldgers. My wife loves Foldgers by the way, so it's not like I'll stop buying it, but I really hope this satoshi coffee is good because hyperbitcoinization won't start until we demand buying coffee with bitcoin like Jewish people demand Kosher drinks.

[BTCPins](https://btcpins.com/)

BTCPins sells cool bitcoin collectible PINS. They're reasonably priced and look great. He only accepts bitcoin because he is a true ride or die freak. He is also one of the meetup organizers in Southern California and wears hats sold by Bitcoin author, Knut Svanholm. He's the real deal.

[Strike](https://strike.me/)

Strike would pay me like five or ten bucks if I had you sign up with them via my referral link, but I'm not recommending them for the referral money. This is about recommending services I use. Strike is the best way to send fiat around the world. I also know that many bitcoiners don't like the idea of spending their own bitcoin, Strike gives you the ability to instantaneously convert fiat to bitcoin and vice-versa. I would rather have the hodl never sodl people spend fiat in the circular economy this way.

In a perfect world, Strike would not comply with KYC laws, but like I said, it's the best way to send fiat around the world.(or people on Robosats who could be anywhere in the world.) I also think if a KYC free exchange is to expensive, you're better off stacking a little on a KYC exchange than not stacking at all. Budgets are tight these days. If you can only stack a penny this paycheck, stack that penny with Strike.  Need to send fiat to Mexico, use Strike instead of Western Union.

[Seed Signer](https://seedsigner.com/)

Seed Signer is a raspberry pi with no Wi-Fi. You can make your own or buy one from the store. The seed signer does not have a secure element, but it also does not store your seed on the device. Therefore, you must write down your seed and enter it into the device every time you plug it in. This sounds like a pain in the ass, and it is if you do it that way, but it comes with a camera and a unique neat feature. You can create a QR code using a pen and paper.(You'll need access to a printer too) Actually, I recommend using a pencil and paper. It's easy to make a mistake so you might want to erase it. You can always go over it with a felt tip pen later if you're worried about a man in the middle attack. You can also use it for nostr keys I think, but I have not tried this feature. I would not  trust all my bitcoin with any wallet, but this is an excellent wallet to use as part of a multisig with Sparrow Wallet or Specter Desktop.

[Get Alby](https://getalby.com)

Get Alby is my favorite desktop wallet. I've made some videos about them here and highly recomend it because you can use it as a custodial wallet or hook it up to your own node. I also respect this product a lot. Back in 2017 or 2018 we had the Joule browser extension, but you had basically had to be a lightning engineer to get it to work. I wasted many hours of my life away trying to get it to work on my browser with no dice. Alby is about 100X improvement over the old Joule days. They also have some cool nostr features and make it easy to login to websites.  Full disclosure, I have no idea how they make money.

These are not all the products I use, and I will add more over time. If you have a bitcoin side hustle or sell a bitcoin related product, let me know about it. I'm always interested in learning about more bitcoin companies.  I'm still searching for the best non-custodial lightning wallet, but it is too early to have an opinion yet. I a also spent my spare time learning about multi-sig during the pandemic and collaborative custody has some of the best trade offs, but there are things I like about them and things I don't.  Casa is great for privacy, and I like the hardware wallets, but the ETH thing makes me nervous. I don't have any eth, but if I die, I don't want my wife to sign into Casa and see a big Ethereum ad. Unchained Capital has an awesome bitcoin only collaborative custody model, but retrieving the key requires  wills and trusts that I don't understand. I like the self sovereign solution unchained provides, but it's too technical for my wife. Nunchuck is also great for the hardcore, but my wife wants to punch me in the face when I talk about it.
Blogging Bitcoin
nostr:npub1wkljx5c6a8uccc5etws8ry0y3r4dgavh2dcav0tal4rtmcdl4z2sfu5u0t.

This blog is written with 🧡 using the value 4 value model. Please subscribe on highlighter.news and zap
⚡sats. 
